version: "3"

tasks:
  run:
    desc: "Run service"
    cmds:
      - go run ./cmd/sso/main.go --config=./config/local.yaml 
  
  migrate:
    desc: "Apply or rollback migrations base on the action flag"
    cmds:
      - CONFIG_PATH=./config/local.yaml go run ./cmd/migrator/main.go --migrations-path=./migrations --action={{.ACTION}} --force-version={{.VERSION}}

  migrate-up:
    desc: "Apply migrations"
    cmds:
      - task: migrate
        vars:
          ACTION: up
          VERSION: "{{default 0}}"

  migrate-down:
    desc: "Rollback migrations"
    cmds:
      - task: migrate
        vars:
          ACTION: down
          VERSION: "{{default 0}}"

  set-migration-version:
    desc: "Set force migrations version"
    cmds:
      - task: migrate
        vars:
          ACTION: force
          VERSION: "{{.VERSION}}"